name: .NET
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release .\GitHubActions
      - name: dotnet publish
        run: |
          dotnet publish -c Release -o GitHubActionsCore .\GitHubActions
      - name: Deploy to IIS
        run: |
          iisreset /stop
          Copy-Item ./GitHubActions/* C:/inetpub/wwwroot/GitHubActions -Recurse -Force
          iisreset /start
